### ISSUE TITLE
Killed:9 occurring on Arm ( M ) cpu Mac's

### ISSUE THREAD

**Issue by NorthernMan54** [prebuild/prebuild-install#201] opened 2024-11-22 01:14 UTC
We are seeing the issue with Homebridge - https://github.com/homebridge/homebridge/issues/3726 and users updating NodeJS, triggering prebuild-install with this package of ours - https://github.com/homebridge/node-pty-prebuilt-multiarch.

The issue has only been reported from end users on MacOS, running on the Arm CPU.  Have not looked in detail at users OS version, but the reports have been Mac Sequoia 15.1.  Also it is occurring on multiple versions of NodeJS ( 18, 20 and 22 )

After digging into the code, determined that this is where the issue is occurring

https://github.com/prebuild/prebuild-install/blob/668d7a6a99c9ec08da9b9ecf6549022a3e32f37c/download.js#L114

```
npm error prebuild-install info unpack resolved to /Users/sgracey/npm/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build/Release/pty.node
npm error sh: line 1: 59327 Killed: 9               prebuild-install --verbose
npm error gyp info it worked if it ends with ok
```

Am putting this out there for others who may be struggling with a similar issue.

**Comment by kmnedd** [comment] 2024-11-22 02:26
As stated above, I was able to install v22.11.0.  I had to reinstall Xcode beforehand as it seem to get corrupted as a result of the failure to load v20.10.0.

**Comment by vweevers** [comment] 2024-11-22 12:43
That line loads the native addon as a test. So the problem is likely in the native addon, not in `prebuild-install`. First, confirm that the correct prebuild is chosen (i.e. for Arm). If so, attach a native debugger to find the issue. Good luck! I'll go ahead and close this, but if you have new evidence that `prebuild-install` might be the culprit, we can reopen.

https://github.com/prebuild/prebuild-install/blob/668d7a6a99c9ec08da9b9ecf6549022a3e32f37c/download.js#L114

**Closed by vweevers** 2024-11-22 12:43 UTC
