### ISSUE TITLE
Does this work with yarn?

### ISSUE THREAD

**Issue by farism** [prebuild/prebuild-install#39] opened 2017-08-02 23:41 UTC
I noticed that standalone mode is determined by checking the `_from` field in the modules `package.json`, which is only created by `npm` clients and not `yarn`. Is there any better way for determining if a module was installed as a dependency?

**Comment by jayalfredprufrock** [comment] 2017-08-19 17:55
I hit this problem too using `prebuild-install`. Apparently this was fixed for `prebuild --install` to properly handle the yarn case (https://github.com/mafintosh/prebuild/issues/132, https://github.com/mafintosh/prebuild/pull/150) So either this is a regression or a new but related problem, or this never got fixed in `prebuild-install`. Something still isn't right though, because reinstalling my project using `npm` allowed prebuild-install to download everything as expected.

**Comment by zkochan** [comment] 2018-02-05 17:29
This doesn't work with [pnpm](https://github.com/pnpm/pnpm) as well. The issue is the same as with Yarn. pnpm only unpacks the dependencies, it doesn't update their `package.json` files

**Comment by ralphtheninja** [comment] 2018-02-05 18:36
> Does this work with yarn?

It seems to work. I tried installing dependencies using yarn and got prebuilt leveldown and I tried yarn inside leveldown git repository and it builds.

> Is there any better way for determining if a module was installed as a dependency?

Not sure what you mean by better, if this works :smile: Personally, I don't know of any other way.

**Closed by ralphtheninja** 2018-02-05 18:36 UTC

**Comment by joneian** [comment] 2018-03-13 14:03
I can't see how this is fixed. 
https://github.com/prebuild/prebuild-install/blob/master/bin.js#L47
Still checks for `_from` which doesn't exist for yarn installed dependencies. 
For me it just says:
```
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info install installing standalone, skipping download.
```

**Comment by zkochan** [comment] 2018-03-13 14:31
No, if the PM is not npm, that check is not done

https://github.com/prebuild/prebuild-install/blob/a950e161b0385c86582c74bcac3dccc7c683beab/bin.js#L42

**Comment by geovie** [comment] 2018-10-26 09:35
https://github.com/prebuild/prebuild-install/blob/a950e161b0385c86582c74bcac3dccc7c683beab/bin.js#L42
This check will not work if yarn is installed globally (e.g. on Windows) the `/node_modules/.test(process.cwd())` test will fail

**Comment by rochdev** [comment] 2019-06-17 19:18
Any news on this? Yarn is always installed globally as this is the recommended way to install it and also how it's installed in the official Node Docker image, so the check always fails.

**Comment by vweevers** [comment] 2019-06-17 19:59
Can someone provide exact steps to replicate? (it works fine for me)

**Comment by rochdev** [comment] 2019-06-17 20:29
```sh
brew install yarn
mkdir ~/prebuild-yarn && cd ~/prebuild-yarn
yarn init -y
yarn add prebuild-install
./node_modules/.bin/prebuild-install --verbose
```

**Comment by vweevers** [comment] 2019-06-17 20:40
That's not a real scenario; `prebuild-install` must be called by a run script of another package.

**Comment by develar** [comment] 2019-06-30 18:24
It is bug, and not clear why it is closed. 

```
/usr/local/Cellar/node/12.5.0/bin/node /Volumes/data/Documents/onshape-desktop-shell/node_modules/prebuild-install/bin.js --platform=linux --arch=x64 --target=5.0.6 --runtime=electron --verbose
```

and it is not even printed as warning, nothing if you don't specify `--verbose` flag.

> must be called by a run script of another package.

Then add this info to readme as `bold` — like "yarn and standalone usage is not supported, must be called only from NPM and by NPM and if you want to use prebuld-install to install deps, you need to wrap it as workaround".

**Comment by vweevers** [comment] 2019-06-30 18:35
@develar Yarn is supported to our knowledge (and tests). Can you provide steps to replicate the bug?

**Comment by develar** [comment] 2019-06-30 18:50
@MarshallOfSound Are you aware about this bug? electron-rebuild [executes exactly this code](https://github.com/electron/electron-rebuild/blob/67fa3d779390e0ef5ac5da2597c8bf076905b0ac/src/rebuild.ts#L281), calling prebuild-install directly. Even electron-builder is also affected, even if under the hood `npm rebuild` / `yarn run install` is used and not prebuild-install directly :(

I discovered this issue using `npx electron-builder`.

> Can you provide steps to replicate the bug?

Well, clone `https://github.com/develar/onshape-desktop-shell`, `yarn install`, and then `DEBUG=electron-builder npx electron-builder --linux AppImage` (if you are on Linux, then change OS target `DEBUG=electron-builder npx electron-builder --mac zip`). As stated, opposite to electron-rebuild, electron-builder will use `npm rebuild` under the hood, still, prebuild-install will not use prebuild, instead, will build native **macOS** dependency on macOS for Linux (so, app will be broken as native dependency cannot be loaded).

**Comment by vweevers** [comment] 2019-06-30 19:05
I'm not convinced the bug is in `prebuild-install` per se, with how `electron-rebuild` wraps it. That said, a PR is welcome if there is an easy way to fix it here.

**Comment by develar** [comment] 2019-06-30 19:15
My main concern is that this behaviour is not expected, as expected behaviour by default, that dependency will be installed. But I don't have full picture and I don't know reasons for what this complicated is required.

I am not going to fight against this issue, since another problem here — `prebuild-install` doesn't detect platform/arch is not compatible and can silently build incorrect native module (so, as maintainer of electron-builder, I get issues like "blank windows instead of app"). So, in any case I will use `--force` flag and in case of error, checks is it possible to rebuild from sources (check arch and platform), and if possible, pass `--build-from-source` (otherwise just break build and show error).

I am not sure — is is prebuild-install responsibility to check platform/arch, so, I am not going for now to send PR. Or it is scope of prebuild-install?

**Comment by develar** [comment] 2019-06-30 19:19
```
 • spawning        command=npm rebuild --verbose keytar@4.11.0 cwd=/Volumes/data/Documents/onshape-desktop-shell
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/12.5.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'rebuild',
npm verb cli   '--verbose',
npm verb cli   'keytar@4.11.0'
npm verb cli ]
npm info using npm@6.9.0
npm info using node@v12.5.0
npm info readInstalled object
npm verb rebuild path, id [
npm verb rebuild   '/Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar',
npm verb rebuild   'keytar@4.11.0'
npm verb rebuild ]
npm info build /Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar
npm info lifecycle keytar@4.11.0~preinstall: keytar@4.11.0
npm info linkStuff keytar@4.11.0
npm verb rebuildBundles [ '.bin' ]
npm info lifecycle keytar@4.11.0~install: keytar@4.11.0

> keytar@4.11.0 install /Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.0
prebuild-install info install installing standalone, skipping download.
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/Cellar/node/12.5.0/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild'
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.5.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://atom.io/download/electron
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)\n' +
gyp verb `which` failed     '    at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)\n' +
gyp verb `which` failed     '    at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16\n' +
gyp verb `which` failed     '    at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5\n' +
gyp verb `which` failed     '    at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import sys; print "2.7.10
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir compiling against --target node version: 5.0.6
gyp verb command install [ '5.0.6' ]
gyp verb download using dist-url https://atom.io/download/electron
gyp verb install input version string "5.0.6"
gyp verb install installing version: 5.0.6
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.0.6
gyp verb build dir attempting to create "build" dir: /Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar/build
gyp verb build dir "build" dir needed to be created? /Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar/build/config.gypi
gyp verb config.gypi checking for gypi file: /Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar/config.gypi
gyp verb common.gypi checking for gypi file: /Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/data/.electron-gyp/5.0.6/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Volumes/data/.electron-gyp/5.0.6',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Volumes/data/.electron-gyp/5.0.6/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/data/Documents/onshape-desktop-shell/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb download using dist-url https://atom.io/download/electron
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Volumes/data/.electron-gyp/5.0.6
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
```

"info install installing standalone, skipping download." :(

debug logs, just for record.

**Comment by vweevers** [comment] 2019-06-30 19:47
> My main concern is that this behaviour is not expected, as expected behaviour by default, that dependency will be installed. But I don't have full picture and I don't know reasons for what this complication is required.

These things are often tricky, as `prebuild-install` depends on the caller (whether that's npm, yarn or electron-rebuild) to provide _just enough_ information to detect the desired behavior (download or compile).

For new scenarios, the preferred solution IMO is for the caller to simulate an existing scenario (like the most common `npm install <package>` scenario). When that isn't feasible, we'll happily take a PR. I personally don't have the capacity to investigate this particular scenario.

> I am not sure — is it prebuild-install responsibility to check platform/arch, so, I am not going for now to send PR. Or it is scope of prebuild-install?

These values are taken from npm/yarn ([here](https://github.com/prebuild/prebuild-install/blob/bb3eac6c6f0dc432326e1aa15c7c9f5157ae7fb0/rc.js#L37-L39)) but can be overridden if need be, via `prebuild-install --arch` and `--platform`. Does that help?

**Comment by develar** [comment] 2019-06-30 20:00
> Does that help?

Nope and this is exactly the issue :( I am sure that electron-builder sets all required envs (https://github.com/electron-userland/electron-builder/blob/2623eebd41100ba2daf81632e80e45fbc8ae087e/packages/app-builder-lib/src/util/yarn.ts#L35)

> I personally don't have the capacity to investigate this particular scenario.

Ok. Thanks for clarification and fast feedback. At least now it is clear that such behaviour has some background reasons.
